version: 2
jobs:
  build:
    machine: true
    working_directory: ~/search-guard-docs
    steps:
      - run: sudo apt-get -yq update
      - run: sudo apt-get -yq install openssl libapr1
      - run: sudo apt-get install ncftp
      - checkout
      - run:
          name: Build Docs
          command: |
            bundle install
            bundle exec jekyll build
            ./_release.sh